[package]
name = "bin"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.1.3", features = ["derive"] }
dotenv = "0.15.0"
env_logger = "0.9.0"
ethers-providers = "1.0"
itertools = "0.10.5"
log = "0.4"
rand = "0.8"
rand_xorshift = "0.3"
reqwest = { version = "0.11", default-features = false, features = [ "json", "rustls-tls" ] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.66"
tokio = { version = "1", features = ["full"] }
zkevm = { path = "../zkevm", features = ["tachyon"] }
types = { path = "../types", features = ["test"] }
utils = { path = "../utils" }
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2022_09_10" }

[features]
default = ["tachyon"]
tachyon = []

[[bin]]
name = "setup"
path = "src/setup.rs"

[[bin]]
name = "prove"
path = "src/prove.rs"

[[bin]]
name = "verify"
path = "src/verify.rs"

[[bin]]
name = "mock_testnet"
path = "src/mock_testnet.rs"
