[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.3", features = ["derive"] }
env_logger = "0.9.0"
dotenv = "0.15.0"
log = "0.4"
rand = "0.8"
rand_xorshift = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.66"
zkevm = { path = "../zkevm" }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
mime_guess = "2"
aws-config = "0.6"
aws-sdk-s3 = "0.6"
anyhow = "1.0"
futures = "0.3"
storage = { path = "../storage" }
jsonrpsee = { version = "0.16.2", features = ["full"] }
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
types = { path = "../types", features = ["test"] }
jsonrpsee-core = "0.16.2"
utils = { path = "../utils" }

[[bin]]
name = "prove"
path = "src/prove.rs"

[[bin]]
name = "verify"
path = "src/verify.rs"